### ISSUE TITLE
pyOpenSSL deps need updating

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/osc-ingest-tools#48]
osc_ingest_trino loads boto3, which ultimately needs something in pyOpenSSL.  It should ask nicely, and word on the street is that means both updating pip and pyOpenSSL:

```
python3 -m pip install --upgrade pip
python3 -m pip install "pyOpenSSL>22.1.0"
```

Otherwise, one sees this:

```
[1001910000@jupyterhub-nb-michaeltiemannosc DERA-ingest-pipeline]$ python
Python 3.8.8 (default, Aug 11 2021, 06:52:42) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import osc_ingest_trino as osc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/app-root/lib64/python3.8/site-packages/osc_ingest_trino/__init__.py", line 1, in <module>
    from .boto3_utils import attach_s3_bucket, upload_directory_to_s3
  File "/opt/app-root/lib64/python3.8/site-packages/osc_ingest_trino/boto3_utils.py", line 3, in <module>
    import boto3
  File "/opt/app-root/lib64/python3.8/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/opt/app-root/lib64/python3.8/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/docs/client.py", line 17, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/utils.py", line 37, in <module>
    import botocore.httpsession
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.crypto
  File "/opt/app-root/lib64/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/app-root/lib64/python3.8/site-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

**Comment by dougmellon** [comment]
Mind if I take a crack at this?

**Comment by MichaelTiemannOSC** [comment]
This has fixed itself.
